server_pool:
  - http://localhost:2000
  - http://localhost:3000
  - http://localhost:4000

worker_processes: 4
listen_port: 5001

routing:
  strategy: least_connections

health_check:
  enabled: true
  interval: 15
  timeout: 4

logging:
  level: "INFO"
  file: "./tmp/balancer.log"
