services:
  app1:
    build: .
    environment:
      - APP_NAME=FlaskApp1
    ports:
      - "2000:5000"  # Host port 2000 maps to container port 5000

  app2:
    build: .
    environment:
      - APP_NAME=FlaskApp2
    ports:
      - "3000:5000"  # Host port 3000 maps to container port 5000

  app3:
    build: .
    environment:
      - APP_NAME=FlaskApp3
    ports:
      - "4000:5000"  # Host port 4000 maps to container port 5000
